using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Formatters;
using Microsoft.EntityFrameworkCore;
using MvcMovie.DataAccess;
using MvcMovie.Models;

namespace MvcMovie.Controllers
{
    public class MoviesController : Controller
    {
        private readonly MvcMovieContext _context;

        public MoviesController(MvcMovieContext context)
        {
            _context = context;
        }

        // GET: /Movies
        public IActionResult Index()
        {
            var movies = _context.Movies;
            return View(movies);
        }

        // GET: /Movies/1
        [HttpGet]
        [Route("Movies/{id:int}")]
        public IActionResult Show(int id)
        {
            var movie = _context.Movies.Find(id);

            return View(movie);
        }

        // GET: /Movies/New
        public IActionResult New()
        {
            return View();
        }

        // POST: /Movies
        [HttpPost]
        public IActionResult Index(Movie movie)
        {
            //Take the movie sent in the request and save it to the database
            _context.Movies.Add(movie);
            _context.SaveChanges();

            // The id generated by the database is now on the object we added to the context
            var newMovieId = movie.Id;

            // Redirect to our route /movies/show and pass in the newMovieId for the id parameter
            return RedirectToAction("show", new { id = newMovieId });
        }

        // GET: /Movies/:id/edit
        [Route("/Movies/{id:int}/edit")]
        public IActionResult Edit(int id)
        {
            var movie = _context.Movies.Find(id);

            return View(movie);
        }

        // PUT (via Post): /Movies/:id
        [HttpPost]
        [Route("/Movies/{id:int}")]
        public IActionResult Update(Movie movie)
        {
            _context.Movies.Update(movie);
            _context.SaveChanges();

            return RedirectToAction("show", new { id = movie.Id });
        }
    }
}
